.PHONY: clean All

All:
	@echo "----------Building project:[ contoh_2 - Debug ]----------"
	@cd "contoh_2" && "$(MAKE)" -f  "contoh_2.mk"
clean:
	@echo "----------Cleaning project:[ contoh_2 - Debug ]----------"
	@cd "contoh_2" && "$(MAKE)" -f  "contoh_2.mk" clean
