.PHONY: clean All

All:
	@echo "----------Building project:[ contoh_1 - Debug ]----------"
	@cd "contoh_1" && "$(MAKE)" -f  "contoh_1.mk"
clean:
	@echo "----------Cleaning project:[ contoh_1 - Debug ]----------"
	@cd "contoh_1" && "$(MAKE)" -f  "contoh_1.mk" clean
